/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.33.1
 * source: market_data.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./google/protobuf/timestamp";
import * as pb_1 from "google-protobuf";
export namespace bsopt.marketdata {
    export enum OptionType {
        CALL = 0,
        PUT = 1
    }
    export enum OrderSide {
        BUY = 0,
        SELL = 1
    }
    export enum AlertType {
        PRICE_ALERT = 0,
        TRADE_EXECUTION = 1,
        RISK_WARNING = 2,
        MARGIN_CALL = 3,
        SYSTEM_NOTIFICATION = 4
    }
    export enum AlertSeverity {
        INFO = 0,
        WARNING = 1,
        ERROR = 2,
        CRITICAL = 3
    }
    export class TickerUpdate extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            symbol?: string;
            price?: number;
            change?: number;
            volume?: number;
            timestamp?: dependency_1.google.protobuf.Timestamp;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("symbol" in data && data.symbol != undefined) {
                    this.symbol = data.symbol;
                }
                if ("price" in data && data.price != undefined) {
                    this.price = data.price;
                }
                if ("change" in data && data.change != undefined) {
                    this.change = data.change;
                }
                if ("volume" in data && data.volume != undefined) {
                    this.volume = data.volume;
                }
                if ("timestamp" in data && data.timestamp != undefined) {
                    this.timestamp = data.timestamp;
                }
            }
        }
        get symbol() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set symbol(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get price() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set price(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get change() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set change(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get volume() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set volume(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get timestamp() {
            return pb_1.Message.getWrapperField(this, dependency_1.google.protobuf.Timestamp, 5) as dependency_1.google.protobuf.Timestamp;
        }
        set timestamp(value: dependency_1.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 5, value);
        }
        get has_timestamp() {
            return pb_1.Message.getField(this, 5) != null;
        }
        static fromObject(data: {
            symbol?: string;
            price?: number;
            change?: number;
            volume?: number;
            timestamp?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
        }): TickerUpdate {
            const message = new TickerUpdate({});
            if (data.symbol != null) {
                message.symbol = data.symbol;
            }
            if (data.price != null) {
                message.price = data.price;
            }
            if (data.change != null) {
                message.change = data.change;
            }
            if (data.volume != null) {
                message.volume = data.volume;
            }
            if (data.timestamp != null) {
                message.timestamp = dependency_1.google.protobuf.Timestamp.fromObject(data.timestamp);
            }
            return message;
        }
        toObject() {
            const data: {
                symbol?: string;
                price?: number;
                change?: number;
                volume?: number;
                timestamp?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
            } = {};
            if (this.symbol != null) {
                data.symbol = this.symbol;
            }
            if (this.price != null) {
                data.price = this.price;
            }
            if (this.change != null) {
                data.change = this.change;
            }
            if (this.volume != null) {
                data.volume = this.volume;
            }
            if (this.timestamp != null) {
                data.timestamp = this.timestamp.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.symbol.length)
                writer.writeString(1, this.symbol);
            if (this.price != 0)
                writer.writeDouble(2, this.price);
            if (this.change != 0)
                writer.writeDouble(3, this.change);
            if (this.volume != 0)
                writer.writeUint64(4, this.volume);
            if (this.has_timestamp)
                writer.writeMessage(5, this.timestamp, () => this.timestamp.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): TickerUpdate {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TickerUpdate();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.symbol = reader.readString();
                        break;
                    case 2:
                        message.price = reader.readDouble();
                        break;
                    case 3:
                        message.change = reader.readDouble();
                        break;
                    case 4:
                        message.volume = reader.readUint64();
                        break;
                    case 5:
                        reader.readMessage(message.timestamp, () => message.timestamp = dependency_1.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): TickerUpdate {
            return TickerUpdate.deserialize(bytes);
        }
    }
    export class OptionChainSnapshot extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            underlying?: string;
            options?: OptionQuote[];
            snapshot_time?: dependency_1.google.protobuf.Timestamp;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("underlying" in data && data.underlying != undefined) {
                    this.underlying = data.underlying;
                }
                if ("options" in data && data.options != undefined) {
                    this.options = data.options;
                }
                if ("snapshot_time" in data && data.snapshot_time != undefined) {
                    this.snapshot_time = data.snapshot_time;
                }
            }
        }
        get underlying() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set underlying(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get options() {
            return pb_1.Message.getRepeatedWrapperField(this, OptionQuote, 2) as OptionQuote[];
        }
        set options(value: OptionQuote[]) {
            pb_1.Message.setRepeatedWrapperField(this, 2, value);
        }
        get snapshot_time() {
            return pb_1.Message.getWrapperField(this, dependency_1.google.protobuf.Timestamp, 3) as dependency_1.google.protobuf.Timestamp;
        }
        set snapshot_time(value: dependency_1.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 3, value);
        }
        get has_snapshot_time() {
            return pb_1.Message.getField(this, 3) != null;
        }
        static fromObject(data: {
            underlying?: string;
            options?: ReturnType<typeof OptionQuote.prototype.toObject>[];
            snapshot_time?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
        }): OptionChainSnapshot {
            const message = new OptionChainSnapshot({});
            if (data.underlying != null) {
                message.underlying = data.underlying;
            }
            if (data.options != null) {
                message.options = data.options.map(item => OptionQuote.fromObject(item));
            }
            if (data.snapshot_time != null) {
                message.snapshot_time = dependency_1.google.protobuf.Timestamp.fromObject(data.snapshot_time);
            }
            return message;
        }
        toObject() {
            const data: {
                underlying?: string;
                options?: ReturnType<typeof OptionQuote.prototype.toObject>[];
                snapshot_time?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
            } = {};
            if (this.underlying != null) {
                data.underlying = this.underlying;
            }
            if (this.options != null) {
                data.options = this.options.map((item: OptionQuote) => item.toObject());
            }
            if (this.snapshot_time != null) {
                data.snapshot_time = this.snapshot_time.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.underlying.length)
                writer.writeString(1, this.underlying);
            if (this.options.length)
                writer.writeRepeatedMessage(2, this.options, (item: OptionQuote) => item.serialize(writer));
            if (this.has_snapshot_time)
                writer.writeMessage(3, this.snapshot_time, () => this.snapshot_time.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): OptionChainSnapshot {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new OptionChainSnapshot();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.underlying = reader.readString();
                        break;
                    case 2:
                        reader.readMessage(message.options, () => pb_1.Message.addToRepeatedWrapperField(message, 2, OptionQuote.deserialize(reader), OptionQuote));
                        break;
                    case 3:
                        reader.readMessage(message.snapshot_time, () => message.snapshot_time = dependency_1.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): OptionChainSnapshot {
            return OptionChainSnapshot.deserialize(bytes);
        }
    }
    export class OptionQuote extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            strike?: number;
            expiration?: string;
            type?: OptionType;
            bid?: number;
            ask?: number;
            last?: number;
            volume?: number;
            open_interest?: number;
            implied_vol?: number;
            greeks?: Greeks;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("strike" in data && data.strike != undefined) {
                    this.strike = data.strike;
                }
                if ("expiration" in data && data.expiration != undefined) {
                    this.expiration = data.expiration;
                }
                if ("type" in data && data.type != undefined) {
                    this.type = data.type;
                }
                if ("bid" in data && data.bid != undefined) {
                    this.bid = data.bid;
                }
                if ("ask" in data && data.ask != undefined) {
                    this.ask = data.ask;
                }
                if ("last" in data && data.last != undefined) {
                    this.last = data.last;
                }
                if ("volume" in data && data.volume != undefined) {
                    this.volume = data.volume;
                }
                if ("open_interest" in data && data.open_interest != undefined) {
                    this.open_interest = data.open_interest;
                }
                if ("implied_vol" in data && data.implied_vol != undefined) {
                    this.implied_vol = data.implied_vol;
                }
                if ("greeks" in data && data.greeks != undefined) {
                    this.greeks = data.greeks;
                }
            }
        }
        get strike() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set strike(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get expiration() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set expiration(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get type() {
            return pb_1.Message.getFieldWithDefault(this, 3, OptionType.CALL) as OptionType;
        }
        set type(value: OptionType) {
            pb_1.Message.setField(this, 3, value);
        }
        get bid() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set bid(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get ask() {
            return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
        }
        set ask(value: number) {
            pb_1.Message.setField(this, 5, value);
        }
        get last() {
            return pb_1.Message.getFieldWithDefault(this, 6, 0) as number;
        }
        set last(value: number) {
            pb_1.Message.setField(this, 6, value);
        }
        get volume() {
            return pb_1.Message.getFieldWithDefault(this, 7, 0) as number;
        }
        set volume(value: number) {
            pb_1.Message.setField(this, 7, value);
        }
        get open_interest() {
            return pb_1.Message.getFieldWithDefault(this, 8, 0) as number;
        }
        set open_interest(value: number) {
            pb_1.Message.setField(this, 8, value);
        }
        get implied_vol() {
            return pb_1.Message.getFieldWithDefault(this, 9, 0) as number;
        }
        set implied_vol(value: number) {
            pb_1.Message.setField(this, 9, value);
        }
        get greeks() {
            return pb_1.Message.getWrapperField(this, Greeks, 10) as Greeks;
        }
        set greeks(value: Greeks) {
            pb_1.Message.setWrapperField(this, 10, value);
        }
        get has_greeks() {
            return pb_1.Message.getField(this, 10) != null;
        }
        static fromObject(data: {
            strike?: number;
            expiration?: string;
            type?: OptionType;
            bid?: number;
            ask?: number;
            last?: number;
            volume?: number;
            open_interest?: number;
            implied_vol?: number;
            greeks?: ReturnType<typeof Greeks.prototype.toObject>;
        }): OptionQuote {
            const message = new OptionQuote({});
            if (data.strike != null) {
                message.strike = data.strike;
            }
            if (data.expiration != null) {
                message.expiration = data.expiration;
            }
            if (data.type != null) {
                message.type = data.type;
            }
            if (data.bid != null) {
                message.bid = data.bid;
            }
            if (data.ask != null) {
                message.ask = data.ask;
            }
            if (data.last != null) {
                message.last = data.last;
            }
            if (data.volume != null) {
                message.volume = data.volume;
            }
            if (data.open_interest != null) {
                message.open_interest = data.open_interest;
            }
            if (data.implied_vol != null) {
                message.implied_vol = data.implied_vol;
            }
            if (data.greeks != null) {
                message.greeks = Greeks.fromObject(data.greeks);
            }
            return message;
        }
        toObject() {
            const data: {
                strike?: number;
                expiration?: string;
                type?: OptionType;
                bid?: number;
                ask?: number;
                last?: number;
                volume?: number;
                open_interest?: number;
                implied_vol?: number;
                greeks?: ReturnType<typeof Greeks.prototype.toObject>;
            } = {};
            if (this.strike != null) {
                data.strike = this.strike;
            }
            if (this.expiration != null) {
                data.expiration = this.expiration;
            }
            if (this.type != null) {
                data.type = this.type;
            }
            if (this.bid != null) {
                data.bid = this.bid;
            }
            if (this.ask != null) {
                data.ask = this.ask;
            }
            if (this.last != null) {
                data.last = this.last;
            }
            if (this.volume != null) {
                data.volume = this.volume;
            }
            if (this.open_interest != null) {
                data.open_interest = this.open_interest;
            }
            if (this.implied_vol != null) {
                data.implied_vol = this.implied_vol;
            }
            if (this.greeks != null) {
                data.greeks = this.greeks.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.strike != 0)
                writer.writeDouble(1, this.strike);
            if (this.expiration.length)
                writer.writeString(2, this.expiration);
            if (this.type != OptionType.CALL)
                writer.writeEnum(3, this.type);
            if (this.bid != 0)
                writer.writeDouble(4, this.bid);
            if (this.ask != 0)
                writer.writeDouble(5, this.ask);
            if (this.last != 0)
                writer.writeDouble(6, this.last);
            if (this.volume != 0)
                writer.writeUint32(7, this.volume);
            if (this.open_interest != 0)
                writer.writeUint32(8, this.open_interest);
            if (this.implied_vol != 0)
                writer.writeDouble(9, this.implied_vol);
            if (this.has_greeks)
                writer.writeMessage(10, this.greeks, () => this.greeks.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): OptionQuote {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new OptionQuote();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.strike = reader.readDouble();
                        break;
                    case 2:
                        message.expiration = reader.readString();
                        break;
                    case 3:
                        message.type = reader.readEnum();
                        break;
                    case 4:
                        message.bid = reader.readDouble();
                        break;
                    case 5:
                        message.ask = reader.readDouble();
                        break;
                    case 6:
                        message.last = reader.readDouble();
                        break;
                    case 7:
                        message.volume = reader.readUint32();
                        break;
                    case 8:
                        message.open_interest = reader.readUint32();
                        break;
                    case 9:
                        message.implied_vol = reader.readDouble();
                        break;
                    case 10:
                        reader.readMessage(message.greeks, () => message.greeks = Greeks.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): OptionQuote {
            return OptionQuote.deserialize(bytes);
        }
    }
    export class Greeks extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            delta?: number;
            gamma?: number;
            theta?: number;
            vega?: number;
            rho?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("delta" in data && data.delta != undefined) {
                    this.delta = data.delta;
                }
                if ("gamma" in data && data.gamma != undefined) {
                    this.gamma = data.gamma;
                }
                if ("theta" in data && data.theta != undefined) {
                    this.theta = data.theta;
                }
                if ("vega" in data && data.vega != undefined) {
                    this.vega = data.vega;
                }
                if ("rho" in data && data.rho != undefined) {
                    this.rho = data.rho;
                }
            }
        }
        get delta() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set delta(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get gamma() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set gamma(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get theta() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set theta(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get vega() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set vega(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get rho() {
            return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
        }
        set rho(value: number) {
            pb_1.Message.setField(this, 5, value);
        }
        static fromObject(data: {
            delta?: number;
            gamma?: number;
            theta?: number;
            vega?: number;
            rho?: number;
        }): Greeks {
            const message = new Greeks({});
            if (data.delta != null) {
                message.delta = data.delta;
            }
            if (data.gamma != null) {
                message.gamma = data.gamma;
            }
            if (data.theta != null) {
                message.theta = data.theta;
            }
            if (data.vega != null) {
                message.vega = data.vega;
            }
            if (data.rho != null) {
                message.rho = data.rho;
            }
            return message;
        }
        toObject() {
            const data: {
                delta?: number;
                gamma?: number;
                theta?: number;
                vega?: number;
                rho?: number;
            } = {};
            if (this.delta != null) {
                data.delta = this.delta;
            }
            if (this.gamma != null) {
                data.gamma = this.gamma;
            }
            if (this.theta != null) {
                data.theta = this.theta;
            }
            if (this.vega != null) {
                data.vega = this.vega;
            }
            if (this.rho != null) {
                data.rho = this.rho;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.delta != 0)
                writer.writeDouble(1, this.delta);
            if (this.gamma != 0)
                writer.writeDouble(2, this.gamma);
            if (this.theta != 0)
                writer.writeDouble(3, this.theta);
            if (this.vega != 0)
                writer.writeDouble(4, this.vega);
            if (this.rho != 0)
                writer.writeDouble(5, this.rho);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Greeks {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Greeks();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.delta = reader.readDouble();
                        break;
                    case 2:
                        message.gamma = reader.readDouble();
                        break;
                    case 3:
                        message.theta = reader.readDouble();
                        break;
                    case 4:
                        message.vega = reader.readDouble();
                        break;
                    case 5:
                        message.rho = reader.readDouble();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Greeks {
            return Greeks.deserialize(bytes);
        }
    }
    export class TradeExecution extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            order_id?: string;
            symbol?: string;
            price?: number;
            quantity?: number;
            side?: OrderSide;
            executed_at?: dependency_1.google.protobuf.Timestamp;
            execution_id?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("order_id" in data && data.order_id != undefined) {
                    this.order_id = data.order_id;
                }
                if ("symbol" in data && data.symbol != undefined) {
                    this.symbol = data.symbol;
                }
                if ("price" in data && data.price != undefined) {
                    this.price = data.price;
                }
                if ("quantity" in data && data.quantity != undefined) {
                    this.quantity = data.quantity;
                }
                if ("side" in data && data.side != undefined) {
                    this.side = data.side;
                }
                if ("executed_at" in data && data.executed_at != undefined) {
                    this.executed_at = data.executed_at;
                }
                if ("execution_id" in data && data.execution_id != undefined) {
                    this.execution_id = data.execution_id;
                }
            }
        }
        get order_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set order_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get symbol() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set symbol(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get price() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set price(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get quantity() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set quantity(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get side() {
            return pb_1.Message.getFieldWithDefault(this, 5, OrderSide.BUY) as OrderSide;
        }
        set side(value: OrderSide) {
            pb_1.Message.setField(this, 5, value);
        }
        get executed_at() {
            return pb_1.Message.getWrapperField(this, dependency_1.google.protobuf.Timestamp, 6) as dependency_1.google.protobuf.Timestamp;
        }
        set executed_at(value: dependency_1.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 6, value);
        }
        get has_executed_at() {
            return pb_1.Message.getField(this, 6) != null;
        }
        get execution_id() {
            return pb_1.Message.getFieldWithDefault(this, 7, "") as string;
        }
        set execution_id(value: string) {
            pb_1.Message.setField(this, 7, value);
        }
        static fromObject(data: {
            order_id?: string;
            symbol?: string;
            price?: number;
            quantity?: number;
            side?: OrderSide;
            executed_at?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
            execution_id?: string;
        }): TradeExecution {
            const message = new TradeExecution({});
            if (data.order_id != null) {
                message.order_id = data.order_id;
            }
            if (data.symbol != null) {
                message.symbol = data.symbol;
            }
            if (data.price != null) {
                message.price = data.price;
            }
            if (data.quantity != null) {
                message.quantity = data.quantity;
            }
            if (data.side != null) {
                message.side = data.side;
            }
            if (data.executed_at != null) {
                message.executed_at = dependency_1.google.protobuf.Timestamp.fromObject(data.executed_at);
            }
            if (data.execution_id != null) {
                message.execution_id = data.execution_id;
            }
            return message;
        }
        toObject() {
            const data: {
                order_id?: string;
                symbol?: string;
                price?: number;
                quantity?: number;
                side?: OrderSide;
                executed_at?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
                execution_id?: string;
            } = {};
            if (this.order_id != null) {
                data.order_id = this.order_id;
            }
            if (this.symbol != null) {
                data.symbol = this.symbol;
            }
            if (this.price != null) {
                data.price = this.price;
            }
            if (this.quantity != null) {
                data.quantity = this.quantity;
            }
            if (this.side != null) {
                data.side = this.side;
            }
            if (this.executed_at != null) {
                data.executed_at = this.executed_at.toObject();
            }
            if (this.execution_id != null) {
                data.execution_id = this.execution_id;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.order_id.length)
                writer.writeString(1, this.order_id);
            if (this.symbol.length)
                writer.writeString(2, this.symbol);
            if (this.price != 0)
                writer.writeDouble(3, this.price);
            if (this.quantity != 0)
                writer.writeUint32(4, this.quantity);
            if (this.side != OrderSide.BUY)
                writer.writeEnum(5, this.side);
            if (this.has_executed_at)
                writer.writeMessage(6, this.executed_at, () => this.executed_at.serialize(writer));
            if (this.execution_id.length)
                writer.writeString(7, this.execution_id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): TradeExecution {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TradeExecution();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.order_id = reader.readString();
                        break;
                    case 2:
                        message.symbol = reader.readString();
                        break;
                    case 3:
                        message.price = reader.readDouble();
                        break;
                    case 4:
                        message.quantity = reader.readUint32();
                        break;
                    case 5:
                        message.side = reader.readEnum();
                        break;
                    case 6:
                        reader.readMessage(message.executed_at, () => message.executed_at = dependency_1.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    case 7:
                        message.execution_id = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): TradeExecution {
            return TradeExecution.deserialize(bytes);
        }
    }
    export class PortfolioUpdate extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            portfolio_id?: string;
            total_value?: number;
            cash?: number;
            pnl_today?: number;
            pnl_total?: number;
            positions?: Position[];
            updated_at?: dependency_1.google.protobuf.Timestamp;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [6], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("portfolio_id" in data && data.portfolio_id != undefined) {
                    this.portfolio_id = data.portfolio_id;
                }
                if ("total_value" in data && data.total_value != undefined) {
                    this.total_value = data.total_value;
                }
                if ("cash" in data && data.cash != undefined) {
                    this.cash = data.cash;
                }
                if ("pnl_today" in data && data.pnl_today != undefined) {
                    this.pnl_today = data.pnl_today;
                }
                if ("pnl_total" in data && data.pnl_total != undefined) {
                    this.pnl_total = data.pnl_total;
                }
                if ("positions" in data && data.positions != undefined) {
                    this.positions = data.positions;
                }
                if ("updated_at" in data && data.updated_at != undefined) {
                    this.updated_at = data.updated_at;
                }
            }
        }
        get portfolio_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set portfolio_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get total_value() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set total_value(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get cash() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set cash(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get pnl_today() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set pnl_today(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get pnl_total() {
            return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
        }
        set pnl_total(value: number) {
            pb_1.Message.setField(this, 5, value);
        }
        get positions() {
            return pb_1.Message.getRepeatedWrapperField(this, Position, 6) as Position[];
        }
        set positions(value: Position[]) {
            pb_1.Message.setRepeatedWrapperField(this, 6, value);
        }
        get updated_at() {
            return pb_1.Message.getWrapperField(this, dependency_1.google.protobuf.Timestamp, 7) as dependency_1.google.protobuf.Timestamp;
        }
        set updated_at(value: dependency_1.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 7, value);
        }
        get has_updated_at() {
            return pb_1.Message.getField(this, 7) != null;
        }
        static fromObject(data: {
            portfolio_id?: string;
            total_value?: number;
            cash?: number;
            pnl_today?: number;
            pnl_total?: number;
            positions?: ReturnType<typeof Position.prototype.toObject>[];
            updated_at?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
        }): PortfolioUpdate {
            const message = new PortfolioUpdate({});
            if (data.portfolio_id != null) {
                message.portfolio_id = data.portfolio_id;
            }
            if (data.total_value != null) {
                message.total_value = data.total_value;
            }
            if (data.cash != null) {
                message.cash = data.cash;
            }
            if (data.pnl_today != null) {
                message.pnl_today = data.pnl_today;
            }
            if (data.pnl_total != null) {
                message.pnl_total = data.pnl_total;
            }
            if (data.positions != null) {
                message.positions = data.positions.map(item => Position.fromObject(item));
            }
            if (data.updated_at != null) {
                message.updated_at = dependency_1.google.protobuf.Timestamp.fromObject(data.updated_at);
            }
            return message;
        }
        toObject() {
            const data: {
                portfolio_id?: string;
                total_value?: number;
                cash?: number;
                pnl_today?: number;
                pnl_total?: number;
                positions?: ReturnType<typeof Position.prototype.toObject>[];
                updated_at?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
            } = {};
            if (this.portfolio_id != null) {
                data.portfolio_id = this.portfolio_id;
            }
            if (this.total_value != null) {
                data.total_value = this.total_value;
            }
            if (this.cash != null) {
                data.cash = this.cash;
            }
            if (this.pnl_today != null) {
                data.pnl_today = this.pnl_today;
            }
            if (this.pnl_total != null) {
                data.pnl_total = this.pnl_total;
            }
            if (this.positions != null) {
                data.positions = this.positions.map((item: Position) => item.toObject());
            }
            if (this.updated_at != null) {
                data.updated_at = this.updated_at.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.portfolio_id.length)
                writer.writeString(1, this.portfolio_id);
            if (this.total_value != 0)
                writer.writeDouble(2, this.total_value);
            if (this.cash != 0)
                writer.writeDouble(3, this.cash);
            if (this.pnl_today != 0)
                writer.writeDouble(4, this.pnl_today);
            if (this.pnl_total != 0)
                writer.writeDouble(5, this.pnl_total);
            if (this.positions.length)
                writer.writeRepeatedMessage(6, this.positions, (item: Position) => item.serialize(writer));
            if (this.has_updated_at)
                writer.writeMessage(7, this.updated_at, () => this.updated_at.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PortfolioUpdate {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PortfolioUpdate();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.portfolio_id = reader.readString();
                        break;
                    case 2:
                        message.total_value = reader.readDouble();
                        break;
                    case 3:
                        message.cash = reader.readDouble();
                        break;
                    case 4:
                        message.pnl_today = reader.readDouble();
                        break;
                    case 5:
                        message.pnl_total = reader.readDouble();
                        break;
                    case 6:
                        reader.readMessage(message.positions, () => pb_1.Message.addToRepeatedWrapperField(message, 6, Position.deserialize(reader), Position));
                        break;
                    case 7:
                        reader.readMessage(message.updated_at, () => message.updated_at = dependency_1.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): PortfolioUpdate {
            return PortfolioUpdate.deserialize(bytes);
        }
    }
    export class Position extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            symbol?: string;
            quantity?: number;
            avg_price?: number;
            current_price?: number;
            unrealized_pnl?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("symbol" in data && data.symbol != undefined) {
                    this.symbol = data.symbol;
                }
                if ("quantity" in data && data.quantity != undefined) {
                    this.quantity = data.quantity;
                }
                if ("avg_price" in data && data.avg_price != undefined) {
                    this.avg_price = data.avg_price;
                }
                if ("current_price" in data && data.current_price != undefined) {
                    this.current_price = data.current_price;
                }
                if ("unrealized_pnl" in data && data.unrealized_pnl != undefined) {
                    this.unrealized_pnl = data.unrealized_pnl;
                }
            }
        }
        get symbol() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set symbol(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get quantity() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set quantity(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get avg_price() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set avg_price(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get current_price() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set current_price(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get unrealized_pnl() {
            return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
        }
        set unrealized_pnl(value: number) {
            pb_1.Message.setField(this, 5, value);
        }
        static fromObject(data: {
            symbol?: string;
            quantity?: number;
            avg_price?: number;
            current_price?: number;
            unrealized_pnl?: number;
        }): Position {
            const message = new Position({});
            if (data.symbol != null) {
                message.symbol = data.symbol;
            }
            if (data.quantity != null) {
                message.quantity = data.quantity;
            }
            if (data.avg_price != null) {
                message.avg_price = data.avg_price;
            }
            if (data.current_price != null) {
                message.current_price = data.current_price;
            }
            if (data.unrealized_pnl != null) {
                message.unrealized_pnl = data.unrealized_pnl;
            }
            return message;
        }
        toObject() {
            const data: {
                symbol?: string;
                quantity?: number;
                avg_price?: number;
                current_price?: number;
                unrealized_pnl?: number;
            } = {};
            if (this.symbol != null) {
                data.symbol = this.symbol;
            }
            if (this.quantity != null) {
                data.quantity = this.quantity;
            }
            if (this.avg_price != null) {
                data.avg_price = this.avg_price;
            }
            if (this.current_price != null) {
                data.current_price = this.current_price;
            }
            if (this.unrealized_pnl != null) {
                data.unrealized_pnl = this.unrealized_pnl;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.symbol.length)
                writer.writeString(1, this.symbol);
            if (this.quantity != 0)
                writer.writeDouble(2, this.quantity);
            if (this.avg_price != 0)
                writer.writeDouble(3, this.avg_price);
            if (this.current_price != 0)
                writer.writeDouble(4, this.current_price);
            if (this.unrealized_pnl != 0)
                writer.writeDouble(5, this.unrealized_pnl);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Position {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Position();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.symbol = reader.readString();
                        break;
                    case 2:
                        message.quantity = reader.readDouble();
                        break;
                    case 3:
                        message.avg_price = reader.readDouble();
                        break;
                    case 4:
                        message.current_price = reader.readDouble();
                        break;
                    case 5:
                        message.unrealized_pnl = reader.readDouble();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Position {
            return Position.deserialize(bytes);
        }
    }
    export class Alert extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            alert_id?: string;
            type?: AlertType;
            title?: string;
            message?: string;
            severity?: AlertSeverity;
            created_at?: dependency_1.google.protobuf.Timestamp;
            metadata?: Map<string, string>;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("alert_id" in data && data.alert_id != undefined) {
                    this.alert_id = data.alert_id;
                }
                if ("type" in data && data.type != undefined) {
                    this.type = data.type;
                }
                if ("title" in data && data.title != undefined) {
                    this.title = data.title;
                }
                if ("message" in data && data.message != undefined) {
                    this.message = data.message;
                }
                if ("severity" in data && data.severity != undefined) {
                    this.severity = data.severity;
                }
                if ("created_at" in data && data.created_at != undefined) {
                    this.created_at = data.created_at;
                }
                if ("metadata" in data && data.metadata != undefined) {
                    this.metadata = data.metadata;
                }
            }
            if (!this.metadata)
                this.metadata = new Map();
        }
        get alert_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set alert_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get type() {
            return pb_1.Message.getFieldWithDefault(this, 2, AlertType.PRICE_ALERT) as AlertType;
        }
        set type(value: AlertType) {
            pb_1.Message.setField(this, 2, value);
        }
        get title() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set title(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get message() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set message(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        get severity() {
            return pb_1.Message.getFieldWithDefault(this, 5, AlertSeverity.INFO) as AlertSeverity;
        }
        set severity(value: AlertSeverity) {
            pb_1.Message.setField(this, 5, value);
        }
        get created_at() {
            return pb_1.Message.getWrapperField(this, dependency_1.google.protobuf.Timestamp, 6) as dependency_1.google.protobuf.Timestamp;
        }
        set created_at(value: dependency_1.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 6, value);
        }
        get has_created_at() {
            return pb_1.Message.getField(this, 6) != null;
        }
        get metadata() {
            return pb_1.Message.getField(this, 7) as any as Map<string, string>;
        }
        set metadata(value: Map<string, string>) {
            pb_1.Message.setField(this, 7, value as any);
        }
        static fromObject(data: {
            alert_id?: string;
            type?: AlertType;
            title?: string;
            message?: string;
            severity?: AlertSeverity;
            created_at?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
            metadata?: {
                [key: string]: string;
            };
        }): Alert {
            const message = new Alert({});
            if (data.alert_id != null) {
                message.alert_id = data.alert_id;
            }
            if (data.type != null) {
                message.type = data.type;
            }
            if (data.title != null) {
                message.title = data.title;
            }
            if (data.message != null) {
                message.message = data.message;
            }
            if (data.severity != null) {
                message.severity = data.severity;
            }
            if (data.created_at != null) {
                message.created_at = dependency_1.google.protobuf.Timestamp.fromObject(data.created_at);
            }
            if (typeof data.metadata == "object") {
                message.metadata = new Map(Object.entries(data.metadata));
            }
            return message;
        }
        toObject() {
            const data: {
                alert_id?: string;
                type?: AlertType;
                title?: string;
                message?: string;
                severity?: AlertSeverity;
                created_at?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
                metadata?: {
                    [key: string]: string;
                };
            } = {};
            if (this.alert_id != null) {
                data.alert_id = this.alert_id;
            }
            if (this.type != null) {
                data.type = this.type;
            }
            if (this.title != null) {
                data.title = this.title;
            }
            if (this.message != null) {
                data.message = this.message;
            }
            if (this.severity != null) {
                data.severity = this.severity;
            }
            if (this.created_at != null) {
                data.created_at = this.created_at.toObject();
            }
            if (this.metadata != null) {
                data.metadata = (Object.fromEntries)(this.metadata);
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.alert_id.length)
                writer.writeString(1, this.alert_id);
            if (this.type != AlertType.PRICE_ALERT)
                writer.writeEnum(2, this.type);
            if (this.title.length)
                writer.writeString(3, this.title);
            if (this.message.length)
                writer.writeString(4, this.message);
            if (this.severity != AlertSeverity.INFO)
                writer.writeEnum(5, this.severity);
            if (this.has_created_at)
                writer.writeMessage(6, this.created_at, () => this.created_at.serialize(writer));
            for (const [key, value] of this.metadata) {
                writer.writeMessage(7, this.metadata, () => {
                    writer.writeString(1, key);
                    writer.writeString(2, value);
                });
            }
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Alert {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Alert();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.alert_id = reader.readString();
                        break;
                    case 2:
                        message.type = reader.readEnum();
                        break;
                    case 3:
                        message.title = reader.readString();
                        break;
                    case 4:
                        message.message = reader.readString();
                        break;
                    case 5:
                        message.severity = reader.readEnum();
                        break;
                    case 6:
                        reader.readMessage(message.created_at, () => message.created_at = dependency_1.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    case 7:
                        reader.readMessage(message, () => pb_1.Map.deserializeBinary(message.metadata as any, reader, reader.readString, reader.readString));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Alert {
            return Alert.deserialize(bytes);
        }
    }
}
