[build]
  base = "src/frontend"
  publish = "dist"
  command = "npm install && npm run build"

[context.production.environment]
  NODE_VERSION = "20"

[context.deploy-preview.environment]
  NODE_VERSION = "20"
