"""add_webauthn_and_social_merging_v2

Revision ID: 78755da6f113
Revises:
Create Date: 2026-03-31 15:47:22.501301

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "78755da6f113"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("recipient", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("template_name", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("provider_message_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Double(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_email_logs_status_time",
        "email_logs",
        ["status", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_logs_provider_message_id"),
        "email_logs",
        ["provider_message_id"],
        unique=False,
    )
    op.create_index(op.f("ix_email_logs_recipient"), "email_logs", ["recipient"], unique=False)
    op.create_table(
        "market_ticks",
        sa.Column(
            "time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=True),
        sa.Column("market", sa.String(length=50), nullable=False),
        sa.Column("change", sa.Numeric(precision=15, scale=4), nullable=False),
        sa.Column("side", postgresql.ENUM("buy", "sell", name="order_side"), nullable=True),
        sa.Column("source_id", sa.String(length=100), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("audit_trail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("time"),
    )
    op.create_index(
        "idx_market_ticks_brin",
        "market_ticks",
        ["time"],
        unique=False,
        postgresql_using="brin",
        postgresql_with={"pages_per_range": 16, "autosummarize": "on"},
    )
    op.create_index(
        "idx_market_ticks_symbol_price_time",
        "market_ticks",
        ["symbol", "price", sa.literal_column("time DESC")],
        unique=False,
        postgresql_include=["volume"],
    )
    op.create_index(
        "idx_market_ticks_symbol_time",
        "market_ticks",
        ["symbol", sa.literal_column("time DESC")],
        unique=False,
    )
    op.create_index(op.f("ix_market_ticks_source_id"), "market_ticks", ["source_id"], unique=False)
    op.create_index(op.f("ix_market_ticks_symbol"), "market_ticks", ["symbol"], unique=False)
    op.create_table(
        "option_contracts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("underlying", sa.String(), nullable=False),
        sa.Column("expiry", sa.Date(), nullable=False),
        sa.Column("strike", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "option_type", postgresql.ENUM("call", "put", name="option_type"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("underlying", "expiry", "strike", "option_type"),
    )
    op.create_table(
        "options_prices",
        sa.Column(
            "time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("expiry", sa.Date(), nullable=False),
        sa.Column("strike", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "option_type", postgresql.ENUM("call", "put", name="option_type"), nullable=False
        ),
        sa.Column("bid", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("ask", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("last", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("volume", sa.Integer(), nullable=True),
        sa.Column("open_interest", sa.Integer(), nullable=True),
        sa.Column("implied_volatility", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("delta", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("gamma", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("vega", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("theta", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("rho", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("source_id", sa.String(length=100), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("audit_trail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("time"),
    )
    op.create_index(
        "idx_options_prices_brin",
        "options_prices",
        ["time"],
        unique=False,
        postgresql_using="brin",
        postgresql_with={"pages_per_range": 32, "autosummarize": "on"},
    )
    op.create_index(
        "idx_options_prices_chain",
        "options_prices",
        ["symbol", "expiry", "strike", "option_type", sa.literal_column("time DESC")],
        unique=False,
        postgresql_include=[
            "bid",
            "ask",
            "last",
            "volume",
            "open_interest",
            "implied_volatility",
            "delta",
            "gamma",
            "vega",
            "theta",
            "rho",
        ],
    )
    op.create_index(
        "idx_options_prices_expiry_only",
        "options_prices",
        [sa.literal_column("expiry DESC")],
        unique=False,
    )
    op.create_index(
        "idx_options_prices_symbol_time",
        "options_prices",
        ["symbol", sa.literal_column("time DESC")],
        unique=False,
    )
    op.create_index(op.f("ix_options_prices_expiry"), "options_prices", ["expiry"], unique=False)
    op.create_index(
        op.f("ix_options_prices_option_type"), "options_prices", ["option_type"], unique=False
    )
    op.create_index(
        op.f("ix_options_prices_source_id"), "options_prices", ["source_id"], unique=False
    )
    op.create_index(op.f("ix_options_prices_strike"), "options_prices", ["strike"], unique=False)
    op.create_index(op.f("ix_options_prices_symbol"), "options_prices", ["symbol"], unique=False)
    op.create_table(
        "outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rate_limits",
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("endpoint", sa.String(length=255), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", "endpoint", "window_start"),
    )
    op.create_index(
        "idx_rate_limits_lookup",
        "rate_limits",
        ["user_id", "endpoint", "window_start"],
        unique=False,
    )
    op.create_table(
        "request_logs",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("path", sa.Text(), nullable=True),
        sa.Column("method", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Double(), nullable=True),
        sa.PrimaryKeyConstraint("created_at"),
    )
    op.create_index(
        "idx_request_logs_brin_time",
        "request_logs",
        ["created_at"],
        unique=False,
        postgresql_using="brin",
    )
    op.create_index(
        "idx_request_logs_errors",
        "request_logs",
        ["status_code", sa.literal_column("created_at DESC")],
        unique=False,
        postgresql_where=sa.text("status_code >= 400"),
    )
    op.create_table(
        "rl_episodes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("episode_reward", sa.Double(), nullable=False),
        sa.Column("steps", sa.Integer(), nullable=False),
        sa.Column("hyperparameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rl_episodes_agent_id"), "rl_episodes", ["agent_id"], unique=False)
    op.create_table(
        "security_incidents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("nature_of_breach", sa.Text(), nullable=True),
        sa.Column("approximate_number_data_subjects", sa.Integer(), nullable=True),
        sa.Column("approximate_number_records", sa.Integer(), nullable=True),
        sa.Column("likely_consequences", sa.Text(), nullable=True),
        sa.Column("measures_taken", sa.Text(), nullable=True),
        sa.Column(
            "data_categories_affected", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("reported_to_dpa", sa.Boolean(), nullable=False),
        sa.Column("reported_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "symbols",
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("exchange", sa.String(length=50), nullable=False),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("market_cap", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "last_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("symbol"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=True),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column(
            "tier", postgresql.ENUM("free", "pro", "enterprise", name="user_tier"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("verification_token", sa.String(length=255), nullable=True),
        sa.Column("reset_token", sa.String(length=255), nullable=True),
        sa.Column("reset_token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=False),
        sa.Column("mfa_secret", sa.String(length=255), nullable=True),
        sa.Column("mfa_backup_codes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_users_active_pro",
        "users",
        ["tier"],
        unique=False,
        postgresql_where=sa.text("is_active AND is_verified"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "api_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("prefix", sa.String(length=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_api_keys_key_hash", "api_keys", ["key_hash"], unique=False)
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column(
            "time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("client_ip", postgresql.INET(), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=False),
        sa.Column("latency_ms", sa.Double(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("time"),
    )
    op.create_index(
        "idx_audit_logs_brin_time",
        "audit_logs",
        ["time"],
        unique=False,
        postgresql_using="brin",
        postgresql_with={"pages_per_range": 32, "autosummarize": "on"},
    )
    op.create_index(
        "idx_audit_logs_details_gin",
        "audit_logs",
        ["details"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"details": "jsonb_path_ops"},
    )
    op.create_index(
        "idx_audit_user_time",
        "audit_logs",
        ["user_id", sa.literal_column("time DESC")],
        unique=False,
    )
    op.create_table(
        "better_auth_accounts",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.String(length=255), nullable=False),
        sa.Column("provider_id", sa.String(length=255), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=True),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "better_auth_sessions",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "data_audit_logs",
        sa.Column(
            "time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("table_name", sa.String(), nullable=False),
        sa.Column("operation", sa.String(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("changed_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("full_row", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("query", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("time"),
    )
    op.create_table(
        "email_verification_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "ml_models",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "algorithm",
            postgresql.ENUM(
                "xgboost",
                "lightgbm",
                "neural_network",
                "random_forest",
                "svm",
                "ensemble",
                name="ml_algorithm",
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("hyperparameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("training_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("model_artifact_url", sa.String(length=500), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_production", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version"),
    )
    op.create_index(
        "idx_ml_models_hyperparams_gin",
        "ml_models",
        ["hyperparameters"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"hyperparameters": "jsonb_path_ops"},
    )
    op.create_index(
        "idx_ml_models_metrics_gin",
        "ml_models",
        ["training_metrics"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"training_metrics": "jsonb_path_ops"},
    )
    op.create_table(
        "oauth2_clients",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.String(length=100), nullable=False),
        sa.Column("client_secret", sa.String(length=255), nullable=False),
        sa.Column("redirect_uris", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_confidential", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_oauth2_clients_client_id"), "oauth2_clients", ["client_id"], unique=True
    )
    op.create_table(
        "oauth_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_id", sa.String(length=255), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=True),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("profile_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_id"),
    )
    op.create_table(
        "portfolios",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("cash_balance", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name"),
    )
    op.create_table(
        "user_credentials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("credential_id", sa.String(length=255), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("sign_count", sa.Integer(), nullable=False),
        sa.Column("transports", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("credential_id"),
    )
    op.create_index(
        op.f("ix_user_credentials_user_id"), "user_credentials", ["user_id"], unique=False
    )
    op.create_table(
        "model_drift_baselines",
        sa.Column("model_id", sa.UUID(), nullable=False),
        sa.Column("baseline_accuracy", sa.Double(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["model_id"], ["ml_models.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("model_id"),
    )
    op.create_table(
        "model_embeddings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("model_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("embedding", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["model_id"], ["ml_models.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "model_predictions",
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("model_id", sa.UUID(), nullable=True),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("input_features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("predicted_price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("actual_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("prediction_error", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("actual_value", sa.Numeric(), nullable=True),
        sa.ForeignKeyConstraint(["model_id"], ["ml_models.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("timestamp"),
    )
    op.create_index(
        "idx_model_predictions_features_gin",
        "model_predictions",
        ["input_features"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"input_features": "jsonb_path_ops"},
    )
    op.create_index(
        "idx_model_predictions_model_time",
        "model_predictions",
        ["model_id", sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.create_index(
        "idx_model_predictions_symbol_time",
        "model_predictions",
        ["symbol", sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("strike", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("expiry", sa.Date(), nullable=True),
        sa.Column("option_type", postgresql.ENUM("call", "put", name="option_type"), nullable=True),
        sa.Column("side", postgresql.ENUM("buy", "sell", name="order_side"), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "order_type",
            postgresql.ENUM("market", "limit", "stop", "stop_limit", name="order_type"),
            nullable=False,
        ),
        sa.Column("limit_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("stop_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "filled",
                "partially_filled",
                "cancelled",
                "rejected",
                name="order_status",
            ),
            nullable=False,
        ),
        sa.Column("filled_quantity", sa.Integer(), nullable=False),
        sa.Column("filled_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("broker", sa.String(length=50), nullable=True),
        sa.Column("broker_order_id", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("limit_price >= 0", name="chk_order_limit_price_non_negative"),
        sa.CheckConstraint("quantity > 0", name="chk_order_quantity_positive"),
        sa.CheckConstraint("stop_price >= 0", name="chk_order_stop_price_non_negative"),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolios.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_orders_open",
        "orders",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
        postgresql_where=sa.text("status IN ('pending', 'partially_filled')"),
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column(
            "entry_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("current_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("exit_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("exit_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("realized_pnl", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM("open", "closed", "liquidated", name="position_status"),
            nullable=False,
        ),
        sa.Column("strike", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("expiry", sa.Date(), nullable=True),
        sa.Column("option_type", postgresql.ENUM("call", "put", name="option_type"), nullable=True),
        sa.CheckConstraint("entry_price >= 0", name="chk_position_entry_price_non_negative"),
        sa.CheckConstraint("quantity > 0", name="chk_position_quantity_positive"),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolios.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_positions_active",
        "positions",
        ["portfolio_id", "symbol"],
        unique=False,
        postgresql_where=sa.text("status = 'open'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_positions_active", table_name="positions", postgresql_where=sa.text("status = 'open'")
    )
    op.drop_table("positions")
    op.drop_index(
        "idx_orders_open",
        table_name="orders",
        postgresql_where=sa.text("status IN ('pending', 'partially_filled')"),
    )
    op.drop_table("orders")
    op.drop_index("idx_model_predictions_symbol_time", table_name="model_predictions")
    op.drop_index("idx_model_predictions_model_time", table_name="model_predictions")
    op.drop_index(
        "idx_model_predictions_features_gin",
        table_name="model_predictions",
        postgresql_using="gin",
        postgresql_ops={"input_features": "jsonb_path_ops"},
    )
    op.drop_table("model_predictions")
    op.drop_table("model_embeddings")
    op.drop_table("model_drift_baselines")
    op.drop_index(op.f("ix_user_credentials_user_id"), table_name="user_credentials")
    op.drop_table("user_credentials")
    op.drop_table("portfolios")
    op.drop_table("oauth_accounts")
    op.drop_index(op.f("ix_oauth2_clients_client_id"), table_name="oauth2_clients")
    op.drop_table("oauth2_clients")
    op.drop_index(
        "idx_ml_models_metrics_gin",
        table_name="ml_models",
        postgresql_using="gin",
        postgresql_ops={"training_metrics": "jsonb_path_ops"},
    )
    op.drop_index(
        "idx_ml_models_hyperparams_gin",
        table_name="ml_models",
        postgresql_using="gin",
        postgresql_ops={"hyperparameters": "jsonb_path_ops"},
    )
    op.drop_table("ml_models")
    op.drop_table("email_verification_tokens")
    op.drop_table("data_audit_logs")
    op.drop_table("better_auth_sessions")
    op.drop_table("better_auth_accounts")
    op.drop_index("idx_audit_user_time", table_name="audit_logs")
    op.drop_index(
        "idx_audit_logs_details_gin",
        table_name="audit_logs",
        postgresql_using="gin",
        postgresql_ops={"details": "jsonb_path_ops"},
    )
    op.drop_index(
        "idx_audit_logs_brin_time",
        table_name="audit_logs",
        postgresql_using="brin",
        postgresql_with={"pages_per_range": 32, "autosummarize": "on"},
    )
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.drop_index("idx_api_keys_key_hash", table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(
        "idx_users_active_pro",
        table_name="users",
        postgresql_where=sa.text("is_active AND is_verified"),
    )
    op.drop_table("users")
    op.drop_table("symbols")
    op.drop_table("security_incidents")
    op.drop_index(op.f("ix_rl_episodes_agent_id"), table_name="rl_episodes")
    op.drop_table("rl_episodes")
    op.drop_index(
        "idx_request_logs_errors",
        table_name="request_logs",
        postgresql_where=sa.text("status_code >= 400"),
    )
    op.drop_index("idx_request_logs_brin_time", table_name="request_logs", postgresql_using="brin")
    op.drop_table("request_logs")
    op.drop_index("idx_rate_limits_lookup", table_name="rate_limits")
    op.drop_table("rate_limits")
    op.drop_table("outbox")
    op.drop_index(op.f("ix_options_prices_symbol"), table_name="options_prices")
    op.drop_index(op.f("ix_options_prices_strike"), table_name="options_prices")
    op.drop_index(op.f("ix_options_prices_source_id"), table_name="options_prices")
    op.drop_index(op.f("ix_options_prices_option_type"), table_name="options_prices")
    op.drop_index(op.f("ix_options_prices_expiry"), table_name="options_prices")
    op.drop_index("idx_options_prices_symbol_time", table_name="options_prices")
    op.drop_index("idx_options_prices_expiry_only", table_name="options_prices")
    op.drop_index(
        "idx_options_prices_chain",
        table_name="options_prices",
        postgresql_include=[
            "bid",
            "ask",
            "last",
            "volume",
            "open_interest",
            "implied_volatility",
            "delta",
            "gamma",
            "vega",
            "theta",
            "rho",
        ],
    )
    op.drop_index(
        "idx_options_prices_brin",
        table_name="options_prices",
        postgresql_using="brin",
        postgresql_with={"pages_per_range": 32, "autosummarize": "on"},
    )
    op.drop_table("options_prices")
    op.drop_table("option_contracts")
    op.drop_index(op.f("ix_market_ticks_symbol"), table_name="market_ticks")
    op.drop_index(op.f("ix_market_ticks_source_id"), table_name="market_ticks")
    op.drop_index("idx_market_ticks_symbol_time", table_name="market_ticks")
    op.drop_index(
        "idx_market_ticks_symbol_price_time",
        table_name="market_ticks",
        postgresql_include=["volume"],
    )
    op.drop_index(
        "idx_market_ticks_brin",
        table_name="market_ticks",
        postgresql_using="brin",
        postgresql_with={"pages_per_range": 16, "autosummarize": "on"},
    )
    op.drop_table("market_ticks")
    op.drop_index(op.f("ix_email_logs_recipient"), table_name="email_logs")
    op.drop_index(op.f("ix_email_logs_provider_message_id"), table_name="email_logs")
    op.drop_index("idx_email_logs_status_time", table_name="email_logs")
    op.drop_table("email_logs")
    # ### end Alembic commands ###
