"""Remove user tier column from users table

Revision ID: 1a2b3c4d5e6f
Revises: 04f716667c32
Create Date: 2023-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1a2b3c4d5e6f'
down_revision = '04f716667c32' # Linking to the correct previous revision

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tier')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tier', sa.String(length=20), nullable=True, server_default='free')) # Restore tier column with a default
    # ### end Alembic commands ###