# script.py.mako
# Copyright (c) 2009-2023, Edgewall Software
# Copyright (c) 2023-2023, Alembic Community

def upgrade(context):
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
