# script.py.mako
# Copyright (c) 2009-2023, Edgewall Software
# Copyright (c) 2023-2023, Alembic Community
from alembic import op
import sqlalchemy as sa

revision = 'b9d668bd800f'
down_revision = None # This might need to be adjusted if 'b9d668bd800f' is not the base

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tier')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tier', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###