FROM timescale/timescaledb:latest-pg15

USER root

# Install dependencies and pgvector
RUN apt-get update && \
    apt-get install -y git build-essential postgresql-server-dev-15 && \
    git clone --branch v0.5.1 https://github.com/pgvector/pgvector.git && \
    cd pgvector && \
    make && \
    make install && \
    cd .. && \
    rm -rf pgvector && \
    apt-get remove -y git build-essential postgresql-server-dev-15 && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*
