# Stage 1: Builder
FROM node:20-alpine AS builder

WORKDIR /app

COPY src/auth-service/package*.json ./
RUN npm install

COPY src/auth-service/ ./
RUN npm run build

# Stage 2: Final
FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/src ./src

EXPOSE 4000

ENV NODE_ENV=production

CMD ["node", "dist/index.js"]
