listen_addresses = '*'
shared_buffers = 512MB
effective_cache_size = 1536MB
work_mem = 32MB
maintenance_work_mem = 256MB
max_worker_processes = 8
max_parallel_workers_per_gather = 2
max_parallel_workers = 4
wal_level = replica
checkpoint_completion_target = 0.9
random_page_cost = 1.1
effective_io_concurrency = 200
default_statistics_target = 200
jit = off
timescaledb.max_background_workers = 4
shared_preload_libraries = 'timescaledb'
