FROM python:3.12.13-slim-bookworm
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends build-essential curl && rm -rf /var/lib/apt/lists/*
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.cargo/bin:$PATH"
COPY pyproject.toml .
RUN uv pip install --system --no-cache -r pyproject.toml
COPY src /app/src
COPY protos /app/protos
RUN python -m grpc_tools.protoc -I/app/protos --python_out=/app/src/shared --grpc_python_out=/app/src/shared /app/protos/*.proto
EXPOSE 50051
CMD ["python", "-m", "src.auth.grpc_server"]
