# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/utils/schemas.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "src/utils/schemas.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17src/utils/schemas.proto\x12\rbsopt.schemas"\xd0\x04\n\x12OptionsDataMessage\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x18\n\x10underlying_price\x18\x02 \x01(\x01\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x17\n\x0f\x63ontract_symbol\x18\x04 \x01(\t\x12\x13\n\x0boption_type\x18\x05 \x01(\t\x12\x0e\n\x06strike\x18\x06 \x01(\x01\x12\x12\n\nexpiration\x18\x07 \x01(\t\x12\x0b\n\x03\x62id\x18\x08 \x01(\x01\x12\x0b\n\x03\x61sk\x18\t \x01(\x01\x12\x12\n\nlast_price\x18\n \x01(\x01\x12\x11\n\tmid_price\x18\x0b \x01(\x01\x12\x1f\n\x12implied_volatility\x18\x0c \x01(\x01H\x00\x88\x01\x01\x12\x12\n\x05\x64\x65lta\x18\r \x01(\x01H\x01\x88\x01\x01\x12\x12\n\x05gamma\x18\x0e \x01(\x01H\x02\x88\x01\x01\x12\x12\n\x05theta\x18\x0f \x01(\x01H\x03\x88\x01\x01\x12\x11\n\x04vega\x18\x10 \x01(\x01H\x04\x88\x01\x01\x12\x10\n\x03rho\x18\x11 \x01(\x01H\x05\x88\x01\x01\x12\x0e\n\x06volume\x18\x12 \x01(\x05\x12\x15\n\ropen_interest\x18\x13 \x01(\x05\x12\x1b\n\x0etime_to_expiry\x18\x14 \x01(\x01H\x06\x88\x01\x01\x12\x16\n\tmoneyness\x18\x15 \x01(\x01H\x07\x88\x01\x01\x12\x0e\n\x06source\x18\x16 \x01(\t\x12\x15\n\rquality_score\x18\x17 \x01(\x01\x42\x15\n\x13_implied_volatilityB\x08\n\x06_deltaB\x08\n\x06_gammaB\x08\n\x06_thetaB\x07\n\x05_vegaB\x06\n\x04_rhoB\x11\n\x0f_time_to_expiryB\x0c\n\n_moneyness"J\n\x0fOptionsDataList\x12\x37\n\x0coptions_data\x18\x01 \x03(\x0b\x32!.bsopt.schemas.OptionsDataMessageb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "src.utils.schemas_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_OPTIONSDATAMESSAGE"]._serialized_start = 43
    _globals["_OPTIONSDATAMESSAGE"]._serialized_end = 635
    _globals["_OPTIONSDATALIST"]._serialized_start = 637
    _globals["_OPTIONSDATALIST"]._serialized_end = 711
# @@protoc_insertion_point(module_scope)
