# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\x0f\x62sopt.inference\"\xf4\x01\n\x10InferenceRequest\x12\x18\n\x10underlying_price\x18\x01 \x01(\x01\x12\x0e\n\x06strike\x18\x02 \x01(\x01\x12\x16\n\x0etime_to_expiry\x18\x03 \x01(\x01\x12\x0f\n\x07is_call\x18\x04 \x01(\x05\x12\x11\n\tmoneyness\x18\x05 \x01(\x01\x12\x15\n\rlog_moneyness\x18\x06 \x01(\x01\x12\x1b\n\x13sqrt_time_to_expiry\x18\x07 \x01(\x01\x12\x16\n\x0e\x64\x61ys_to_expiry\x18\x08 \x01(\x01\x12\x1a\n\x12implied_volatility\x18\t \x01(\x01\x12\x12\n\nmodel_type\x18\n \x01(\t\"J\n\x11InferenceResponse\x12\r\n\x05price\x18\x01 \x01(\x01\x12\x12\n\nmodel_type\x18\x02 \x01(\t\x12\x12\n\nlatency_ms\x18\x03 \x01(\x01\x32_\n\x0bMLInference\x12P\n\x07Predict\x12!.bsopt.inference.InferenceRequest\x1a\".bsopt.inference.InferenceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERENCEREQUEST']._serialized_start=37
  _globals['_INFERENCEREQUEST']._serialized_end=281
  _globals['_INFERENCERESPONSE']._serialized_start=283
  _globals['_INFERENCERESPONSE']._serialized_end=357
  _globals['_MLINFERENCE']._serialized_start=359
  _globals['_MLINFERENCE']._serialized_end=454
# @@protoc_insertion_point(module_scope)
