# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: market_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'market_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11market_data.proto\x12\x11\x62sopt.market_data\"-\n\x0cTickerUpdate\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\"H\n\x04Tick\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x0e\n\x06source\x18\x04 \x01(\t\"3\n\tTickBatch\x12&\n\x05ticks\x18\x01 \x03(\x0b\x32\x17.bsopt.market_data.Tick\"7\n\rIngestRequest\x12&\n\x05ticks\x18\x01 \x03(\x0b\x32\x17.bsopt.market_data.Tick\")\n\x0eIngestResponse\x12\x17\n\x0fprocessed_count\x18\x01 \x01(\x05\"F\n\x0eHistoryRequest\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\x12\n\nstart_time\x18\x02 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\x03\"8\n\x0fHistoryResponse\x12%\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x17.bsopt.market_data.Tick2\xbd\x01\n\x0b\x44\x61taService\x12R\n\x0bIngestTicks\x12 .bsopt.market_data.IngestRequest\x1a!.bsopt.market_data.IngestResponse\x12Z\n\x11GetHistoricalData\x12!.bsopt.market_data.HistoryRequest\x1a\".bsopt.market_data.HistoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TICKERUPDATE']._serialized_start=40
  _globals['_TICKERUPDATE']._serialized_end=85
  _globals['_TICK']._serialized_start=87
  _globals['_TICK']._serialized_end=159
  _globals['_TICKBATCH']._serialized_start=161
  _globals['_TICKBATCH']._serialized_end=212
  _globals['_INGESTREQUEST']._serialized_start=214
  _globals['_INGESTREQUEST']._serialized_end=269
  _globals['_INGESTRESPONSE']._serialized_start=271
  _globals['_INGESTRESPONSE']._serialized_end=312
  _globals['_HISTORYREQUEST']._serialized_start=314
  _globals['_HISTORYREQUEST']._serialized_end=384
  _globals['_HISTORYRESPONSE']._serialized_start=386
  _globals['_HISTORYRESPONSE']._serialized_end=442
  _globals['_DATASERVICE']._serialized_start=445
  _globals['_DATASERVICE']._serialized_end=634
# @@protoc_insertion_point(module_scope)
