# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: inference.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.client
import grpclib.const

if typing.TYPE_CHECKING:
    import grpclib.server

from . import inference_pb2


class MLInferenceBase(abc.ABC):

    @abc.abstractmethod
    async def Predict(
        self,
        stream: "grpclib.server.Stream[inference_pb2.InferenceRequest, inference_pb2.InferenceResponse]",
    ) -> None:
        pass

    def __mapping__(self) -> dict[str, grpclib.const.Handler]:
        return {
            "/bsopt.inference.MLInference/Predict": grpclib.const.Handler(
                self.Predict,
                grpclib.const.Cardinality.UNARY_UNARY,
                inference_pb2.InferenceRequest,
                inference_pb2.InferenceResponse,
            ),
        }


class MLInferenceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Predict = grpclib.client.UnaryUnaryMethod(
            channel,
            "/bsopt.inference.MLInference/Predict",
            inference_pb2.InferenceRequest,
            inference_pb2.InferenceResponse,
        )
